#!/usr/bin/env python -u
###############################################################################
#
# File:         run
# RCS:          $Header: $
# Description:  run a file using the command specified on the first line
# Author:       Jim Randell
# Created:      Tue Oct 14 12:52:59 2016
# Modified:     Tue Sep 10 16:38:35 2019 (Jim Randell) jim.randell@gmail.com
# Language:     Python
# Package:      N/A
# Status:       Experimental (Do Not Distribute)
#
# (c) Copyright 2017, Jim Randell, all rights reserved.
#
###############################################################################
# -*- mode: Python; py-indent-offset: 2; -*-

# run a file according to the shebang line:
#
# % run <file>
#
# is the same as:
#
# % ./<file>
#
# if the file is executable, but also works if it isn't

from __future__ import print_function

import sys
import shlex
import subprocess
import os

def fprint(f, *args, **kw):
  print(*args, file=f, **kw)

def usage():
  fprint(sys.stdout, "run [<opts>] <file> [<args>]")
  fprint(sys.stdout, "runs <file> with command specified in the shebang line")
  fprint(sys.stdout, "additional <args> are added to the command")
  fprint(sys.stdout, "valid opts are: (defaults from $RUN_OPT)")
  fprint(sys.stdout, "  -v = verbose, output the command before running it (to stdout")
  fprint(sys.stdout, "  -x = like -v, but doesn't execute the command")
  fprint(sys.stdout, "  -t = output elapsed time of the command execution (to stderr)")
  fprint(sys.stdout, "  -C[<dir>] = cd to <dir> (or directory of <file>)")
  fprint(sys.stdout, "  -s[<file>] = send <file> to stdin of command")
  fprint(sys.stdout, "  -i[<cmd>] = use <cmd> instead of shebang")
  fprint(sys.stdout, "  -n = notify on completion")
  fprint(sys.stdout, "  -c = caffeinate (macOS only)")
  fprint(sys.stdout, "  -h = output (this) usage information")
  fprint(sys.stdout)
  exit()

# parse options, and determine the file to run
cmd = None
verbose = 0
timing = 0
nox = 0
chdir = None
stdin = None
beep = None
caffeinate = 0
shebang = "#!"
argv = sys.argv[1:]

def get_options(argv):
  global cmd, verbose, timing, nox, chdir, stdin, beep, caffeinate
  while argv:
    v = argv.pop(0)
    if v == '--':
      break
    elif v == '-v':
      verbose = 1
    elif v == '-t':
      timing = 1
    elif v == '-x':
      nox = 1
      verbose = 1
    elif v.startswith('-n'):
      beep = v[2:]
    elif v == '-c':
      caffeinate = 1
    elif v.startswith('-C'):
      chdir = v[2:]
    elif v.startswith('-s'):
      stdin = v[2:]
    elif v.startswith('-i'):
      cmd = v[2:]
    elif v.startswith('-'):
      usage()
    else:
      argv.insert(0, v)
      break

if not argv:
  usage()
else:
  if not argv[0].startswith('-'):
    opts = os.getenv("RUN_OPT")
    if opts is not None:
      argv = opts.split() + argv

get_options(argv)

path = os.path.abspath(argv[0])

if cmd is None:
  # read the first line from the file
  # #!<cmd> ...
  with open(path, 'r') as fh:
    s = next(fh)
    # find the #! part
    i = s.find(shebang)
    assert i != -1, "interpreter not found"
    # extract the command (as a string)
    cmd = s[i + len(shebang):].strip()

cmd = shlex.split(cmd)
get_options(cmd)
# turn it into a list: <cmd> <file> <arg> ...
if stdin is None: cmd.append(path)
cmd.extend(argv[1:])

if chdir is not None and not chdir: chdir = os.path.dirname(path)
if stdin is not None and not stdin: stdin = path

# quote argument x
# (Python 3 has shlex.quote())
def quote(x):
  plain = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_+@:.,/'
  (s, q) = (list(), ('' if x else '"'))
  for c in x:
    if c in plain:
      s.append(c)
    else:
      s.extend(('\\', c))
      q = '"'
  return q + (''.join(s)) + q


if cmd:

  if caffeinate: cmd.insert(0, 'caffeinate')

  if verbose and chdir: fprint(sys.stdout, ">>> chdir " + quote(chdir))
  if verbose: fprint(sys.stdout, ">>> " + ' '.join(quote(x) for x in cmd) + (" [stdin=" + stdin + "]" if stdin else ""))

  timer = None
  if timing:
    import time
    try:
      _timer = time.perf_counter
    except AttributeError:
      if sys.platform == 'win32':
        _timer = time.clock
      else:
        _timer = time.time
    timer = _timer()

  # run the command
  if not nox:
    if stdin:
      with open(stdin, 'r') as fh:
        subprocess.call(cmd, cwd=chdir, stdin=fh)
    else:
      subprocess.call(cmd, cwd=chdir)

  if timer:
    t = _timer() - timer
    msg = "[{name}] elapsed time: {t:.7f}s".format(t=t, name=os.path.basename(argv[0]))
    u = 's'
    if t < 1.0: (t, u) = (1000 * t, 'ms')
    if t < 1.0: (t, u) = (1000 * t, 'us')
    msg += " ({t:.2f}{u})".format(t=t, u=u)
    fprint(sys.stderr, msg)

  if beep is not None:
    if beep:
      # run it as a command
      beep = shlex.split(beep)      
      subprocess.call(beep)
    else:
      fprint(sys.stderr, "\007", end="")

#
# possible future enhancements:
#
# * we could consider just calling the file if there's no interpreter and it's executable
#
# * allow some way of mentioning {file}, {args} in the interpreter (otherwise add them to the end)
#
